i626: remove load-data-files json key from problem yaml files
pc2ccs/pc2v9 pull request #675
Opened 2023-01-31 17:43 UTC by lane55

### Description of what the PR does

remove load-data-files key/line from export to problem.yaml
remove load-data-files key/line from export to problemset.yaml

keep load-data-files key/line in export to contest.yaml

### Issue which the PR fixes

Fixes 626 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)

Microsoft Windows [Version 10.0.19044.2130]

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

start server, --load problemflagtest
start admin
export using Run Contest -> Export -> Export Yaml
Select Save

### Expected

There should be no load-data-files line 
in sumit/problem.yaml nor in problemset.yaml

### Actual

in sumit/problem.yaml
```
   load-data-files: true
```

in sumit/problemset.yaml
```
   load-data-files: true
```

2023-01-31 18:01 UTC, johnbrvc approved these changes
Seems to work for me.
By the way, on the PR main page, it does not automatically detect that this closes issue 626 (on the right pane).  I thought it should detect that, maybe you need "- fixes #626" or some such on the PR title?

2023-03-03 10:52 UTC, clevengr requested changes
I question whether the change implemented by this PR is reasonable.  Specifically, as I understand the PR it removes support for the inclusion of `load_data_files` from `problem.yaml` and also from `problemset.yaml`, and causes it to only be recognized/imported/exported to/from `contest.yaml`.

This is the same thing as saying that the `load_data_files` attribute is (solely) a _contest-wide_ attribute.  However, this is NOT accurate:  the "load-data-files" property is specified in the Admin>Configure>Problem>Edit screen _on a per-problem basis_.  Having it specified per-problem (which is appropriate) in the Admin GUI and specified (solely) contest-wide in YAML (as I believe is what is proposed by this PR) produces contradictory configuration information.

Note:  if the PR was to ADD support for load-data-files to `contest.yaml`, causing it to be a "global _default_ value" which could then be overridden by problem-specific entries in `problem.yaml`, much like `timelimit` and `output_limit` work currently, I'd be OK with that.  But I do NOT think it's appropriate to _remove_ support for it in `problem.yaml` -- it's a _problem-specific setting_.  

(I could go either way on keeping it, or removing it, from `problemset.yaml`).

2023-03-03 10:54 UTC, clevengr commented
And yes, as @johnbrvc pointed out, simply putting the Issue Number in the PR does not cause it to close that Issue; the Issue number must be preceded by a word like "Closes" or "Fixes".  PR #685 changes the PR template to (hopefully) clarify this.

2023-03-04 18:36 UTC, lane55 commented
closed, changes required require additional analysis and testing.

2023-03-04 18:36 UTC, closed without merging