i881: update scoreboard JSON to CLICS 2022-07
pc2ccs/pc2v9 pull request #814
Opened 2023-09-22 13:35 UTC by lane55

### Description of what the PR does

This change upgrades the Scoreboard JSON report to the standard.

The standard is at: https://ccs-specs.icpc.io/2022-07/contest_api#scoreboard-format

Adds event feed wrapper and rows array wrapper

### Issue which the PR addresses

#881

### Environment in which the PR was developed (OS,IDE, Java version, etc.)

Microsoft Windows [Version 10.0.19044.2130]

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)

Create a Scoreboard JSON report

Does the output JSON have the following 5 "new" elements?

1 contest_time
2 event_id
3 rows  - array of team scoring rows
4 state
5 time

A skel sample of new elements
```
{
    "contest_time": "5:10:26.783",
    "event_id": "23296",
    "rows": [
        {
            "problems": [
            ...

            "rank": 1,
            "score": {
                "num_solved": 11,
                "total_time": 1443
            },
            "team_id": "48"
        },
        ...

    "state": {
        "end_of_updates": null,
        "ended": "2023-05-29T14:46:55.000-04:00",
        "finalized": "2023-05-29T14:57:19.750-04:00",
        "frozen": "2023-05-29T13:46:55.000-04:00",
        "started": "2023-05-29T09:46:55.000-04:00",
        "thawed": null
    },
    "time": "2023-05-29T14:57:21.783-04:00"
}
```

2023-09-23 03:08 UTC, troy2914 requested changes
I am confused what CLICSContestState has to with this scoreboard change?
I did not see if referenced in either of the other two classes?

2023-09-23 16:03 UTC, troy2914 approved these changes
looked more closely did see CLICSContesttate refenced.

2023-09-23 17:42 UTC, lane55 commented
> I am confused what CLICSContestState has to with this scoreboard change?
> I did not see if referenced in either of the other two classes?

CLICSContestState , at this time, is a event feed wrapper for the scoreboard JSON.
CLICSScoreboard is a single team's scoreboard data
During the quarterly refactor/CI/improvments there is a note to rename those classes as  part of
the effort to upgrade pc2 to meet the CLICS 2022-07 standard

2023-09-23 17:42 UTC, merged

2023-11-25 01:08 UTC, troy2914 commented
correction this is for #811