I885: Fixed typo (Utilites->Utilities) in file names and class usages
pc2ccs/pc2v9 pull request #890
Opened 2023-12-07 21:41 UTC by zilong-yang

### Description of what the PR does

Fixed typos in class name `JudgementUtilites` and `JudgementUtilitesTest` and their usages in other classes.

### Issue which the PR addresses
Fixes #885 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
MacOS Ventura
Jetbrains IntelliJ
Java 1.8 (Amazon Corretto)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
1. Run unit tests in _JudgementUtilitiesTest.java_ and make sure all tests still pass

2023-12-09 23:51 UTC, johnbrvc commented on src/edu/csus/ecs/pc2/services/web/EventFeedStreamer.java
Copyright date should be updated.

2023-12-09 23:51 UTC, johnbrvc commented on src/edu/csus/ecs/pc2/ui/EditRunPane.java
Copyright should be updated.

2023-12-09 23:52 UTC, johnbrvc commented on test/edu/csus/ecs/pc2/core/execute/JudgementUtilitiesTest.java
Copyright should be updated.

2023-12-09 23:55 UTC, johnbrvc requested changes
Loaded and build and ran tests Ok (why shouldn't it?)
Just the copyright dates that should be updated.

2023-12-11 00:30 UTC, zilong-yang commented on src/edu/csus/ecs/pc2/services/web/EventFeedStreamer.java
done!

2023-12-11 00:30 UTC, zilong-yang commented on src/edu/csus/ecs/pc2/ui/EditRunPane.java
done!

2023-12-11 00:30 UTC, zilong-yang commented on test/edu/csus/ecs/pc2/core/execute/JudgementUtilitiesTest.java
done!

2023-12-11 13:52 UTC, johnbrvc approved these changes

2023-12-11 13:53 UTC, johnbrvc commented on src/edu/csus/ecs/pc2/services/web/EventFeedStreamer.java
For future reference, only the CREATOR of a comment can resolve it for PC2.

2023-12-11 13:53 UTC, johnbrvc commented on src/edu/csus/ecs/pc2/ui/EditRunPane.java
For future reference, only the CREATOR of a comment can resolve it for PC2.

2023-12-11 13:53 UTC, johnbrvc commented on test/edu/csus/ecs/pc2/core/execute/JudgementUtilitiesTest.java
For future reference, only the CREATOR of a comment can resolve it for PC2.

2023-12-17 19:47 UTC, clevengr approved these changes
Looks good; adding an approval.  I'll also merge the PR.

2023-12-17 19:47 UTC, merged