I870: Added Enable/Disable Problem Display
pc2ccs/pc2v9 pull request #903
Opened 2023-12-22 22:45 UTC by SamanwaySadhu

### Description of what the PR does
The file submission buttons are enabled/disabled with the contest clock using the function `setButtonsActive` in `SubmitRunPane`. Added `getProblemComboBox().setEnabled` to enable/disable the Problem drop-down list in the same function and it will be synced with the file submission buttons getting enabled /disabled.

### Issue which the PR addresses
Fixes #870 

### Environment in which the PR was developed (OS, IDE, Java version, etc.)
Windows 10, Eclipse 2021-12 R, JDK 8u381 (1.8)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
- Run the Ant script `build.xml` in the `pc2v9` project.
- Start a PC2 server, loading a sample contest such as "SumitHello".
- Start a PC2 Admin (Do not start a contest yet).
- Start a PC2 Team.
- You should see in the top left in Red "STOPPED" denoting the contest is stopped. Now the problem pane will be grayed out and you'll not be able to interact and view the problem names there.
- Start the contest.
- The problem pane will now be active, and you can view the problem names now.
![image](https://github.com/pc2ccs/pc2v9/assets/24360328/fd950c18-fbb9-4eeb-bdb8-cd50c6fed06b)

2023-12-23 21:20 UTC, johnbrvc requested changes
The "**Problem**" drop-down on the "**Request Clarification**" tab should also be disabled since you can see the problems there as well.    As a _Continuous Improvement_ (CI), I _might_ go as far as to say that in addition to the "**Problem**" drop-down on the "**Submit Run**" tab, that you also disable the "**Language**" drop-down as well until the contest started.  IMHO, it seems there is no valid reason to show them which languages are supported until the contest begins, and, for consistency, it probably makes sense to disable the entire GUI on the "**Submit Run**" tab until the contest is started.

Add these as separate commits: 1) **Problem** drop-down on **Request Clarification**  and 2) CI:  **Language** drop-down on **Submit Run** tab.

2023-12-24 06:27 UTC, SamanwaySadhu commented
> The "**Problem**" drop-down on the "**Request Clarification**" tab should also be disabled since you can see the problems there as well. As a _Continuous Improvement_ (CI), I _might_ go as far as to say that in addition to the "**Problem**" drop-down on the "**Submit Run**" tab, that you also disable the "**Language**" drop-down as well until the contest started. IMHO, it seems there is no valid reason to show them which languages are supported until the contest begins, and, for consistency, it probably makes sense to disable the entire GUI on the "**Submit Run**" tab until the contest is started.
> 
> Add these as separate commits: 1) **Problem** drop-down on **Request Clarification** and 2) CI: **Language** drop-down on **Submit Run** tab.

Updated

2023-12-24 18:21 UTC, clevengr approved these changes
The code changes are straightforward and look correct to me.  I built the branch on my local system and tested it; everything works as expected/intended.  Adding an Approval.

2023-12-24 19:33 UTC, johnbrvc commented on src/edu/csus/ecs/pc2/ui/SubmitClarificationPane.java
Very picky, but can you update the copyright year to 2023?

2023-12-24 19:33 UTC, johnbrvc requested changes
Very minor/picky change: update copyright date on `SubmitClarificationPane`

2023-12-25 01:13 UTC, johnbrvc approved these changes
Built, tested.  Looks good to me.

2023-12-25 14:52 UTC, merged