i_911 Make some aesthetic changes to the index html standings pages
pc2ccs/pc2v9 pull request #915
Opened 2024-01-17 03:07 UTC by johnbrvc

### Description of what the PR does
This PR makes the "**index.html**" standings web pages (public and secret) more aesthetically pleasing by toning down the bright colors and putting rounded corners on the cells in the table.

### Issue which the PR addresses
Fixes #911 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Ubuntu 22.04.3
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
1) Load a contest that has submitted and judged runs (I used the PacNW 2022 Regional)
2) Start a scoreboard client and log in to force generation of the HTML pages
3) Look at the generated **index.html** (screen shot below).
<img width="1483" alt="image" src="https://github.com/pc2ccs/pc2v9/assets/5657363/a6a2db32-4b02-41f7-b249-d5fd82cd8b64">

2024-01-19 00:26 UTC, troy2914 requested changes
also maybe the samps/web/xsl xsl should be updated like index.xsl was changed?

2024-01-19 00:27 UTC, troy2914 commented
> Can you please update samps/web/standings.css too?

or maybe that file should be deleted now that it's in data/xsl ?

2024-01-19 00:29 UTC, troy2914 commented
> also maybe the samps/web/xsl xsl should be updated like index.xsl was changed?

actually,  thinking when the groups gets committed those samps/web/xsl are unneeded?

2024-01-21 19:19 UTC, johnbrvc commented
> > also maybe the samps/web/xsl xsl should be updated like index.xsl was changed?
> 
> actually, thinking when the groups gets committed those samps/web/xsl are unneeded?

Probably not.

The real "pc2" provided `data/xsl/index.xsl` will have to be fixed to provide links to other groups' standings pages (assuming, such other groups exist).  In addition, it will have to be aware - somehow - of what group **IT** is, so it doesn't include a link to itself in the list of links.  That is, we can't simply `for-each` group, generate a standings link - or it would generate a link to itself.  For **_PacNW_**, it looks like we'll need a custom one as well, since you add other things to the standings page (technical notes link, sample data link), as well as don't include the "other" division's groups.  A D1 page will not include all the D2 links, only a link to the "D2" page.  I'm not sure how that will work.  At GNY we provide a link on the desktop to the "problem set page", which has links to the problem statements (all zipped or individual pdf), as well as links to the sample data (all zipped up, or individual files) on THAT page.  You guys do it a bit differently.
<img width="724" alt="image" src="https://github.com/pc2ccs/pc2v9/assets/5657363/7cef936c-1d59-44b2-ba51-144bb7b4a24d">

2024-01-21 21:03 UTC, troy2914 commented
> > > also maybe the samps/web/xsl xsl should be updated like index.xsl was changed?
> > 
> > 
> > actually, thinking when the groups gets committed those samps/web/xsl are unneeded?
> 
> Probably not.
> 
> The real "pc2" provided `data/xsl/index.xsl` will have to be fixed to provide links to other groups' standings pages (assuming, such other groups exist). In addition, it will have to be aware - somehow - of what group **IT** is, so it doesn't include a link to itself in the list of links. That is, we can't simply `for-each` group, generate a standings link - or it would generate a link to itself. For **_PacNW_**, it looks like we'll need a custom one as well, since you add other things to the standings page (technical notes link, sample data link), as well as don't include the "other" division's groups. A D1 page will not include all the D2 links, only a link to the "D2" page. I'm not sure how that will work. At GNY we provide a link on the desktop to the "problem set page", which has links to the problem statements (all zipped or individual pdf), as well as links to the sample data (all zipped up, or individual files) on THAT page. You guys do it a bit differently. <img alt="image" width="724" src="https://private-user-images.githubusercontent.com/5657363/298405996-7cef936c-1d59-44b2-ba51-144bb7b4a24d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NzEyMjcsIm5iZiI6MTcwNTg3MDkyNywicGF0aCI6Ii81NjU3MzYzLzI5ODQwNTk5Ni03Y2VmOTM2Yy0xZDU5LTQ0YjItYmE1MS0xNDRiYjdiNGEyNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMjEwMjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFjMjcwNTlkYTg3ZmUxMGYzYjVmOTEyNDQzZmJiZjc0MTE2YWY5YmExNDE5YTU2NTAyNDBmOGFlZWMyYzU3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nek0n7pPKlCTdk9TNh03hcK7zABEoX1pjwqi_m8m5ME">

Okay, in that case,  can we update the samps/web stuff to follow the changes made to the data/xsl bits.

2024-01-24 12:41 UTC, johnbrvc commented
> > > > also maybe the samps/web/xsl xsl should be updated like index.xsl was changed?
> > > 
> > > 
> > > actually, thinking when the groups gets committed those samps/web/xsl are unneeded?
> > 
> > 
> > Probably not.
> > The real "pc2" provided `data/xsl/index.xsl` will have to be fixed to provide links to other groups' standings pages (assuming, such other groups exist). In addition, it will have to be aware - somehow - of what group **IT** is, so it doesn't include a link to itself in the list of links. That is, we can't simply `for-each` group, generate a standings link - or it would generate a link to itself. For **_PacNW_**, it looks like we'll need a custom one as well, since you add other things to the standings page (technical notes link, sample data link), as well as don't include the "other" division's groups. A D1 page will not include all the D2 links, only a link to the "D2" page. I'm not sure how that will work. At GNY we provide a link on the desktop to the "problem set page", which has links to the problem statements (all zipped or individual pdf), as well as links to the sample data (all zipped up, or individual files) on THAT page. You guys do it a bit differently. <img alt="image" width="724" src="https://private-user-images.githubusercontent.com/5657363/298405996-7cef936c-1d59-44b2-ba51-144bb7b4a24d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NzEyMjcsIm5iZiI6MTcwNTg3MDkyNywicGF0aCI6Ii81NjU3MzYzLzI5ODQwNTk5Ni03Y2VmOTM2Yy0xZDU5LTQ0YjItYmE1MS0xNDRiYjdiNGEyNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMjEwMjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFjMjcwNTlkYTg3ZmUxMGYzYjVmOTEyNDQzZmJiZjc0MTE2YWY5YmExNDE5YTU2NTAyNDBmOGFlZWMyYzU3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nek0n7pPKlCTdk9TNh03hcK7zABEoX1pjwqi_m8m5ME">
> 
> Okay, in that case, can we update the samps/web stuff to follow the changes made to the data/xsl bits.

I guess the question is, should we make this a separate issue?  These XSL changes are only relevant for "group" type standings, which is really not the scope of this issue/PR.

2024-01-25 19:37 UTC, troy2914 approved these changes

2024-01-27 15:50 UTC, merged