solves i995, i968
pc2ccs/pc2v9 pull request #996
Opened 2024-07-25 23:32 UTC by kkarakas

Before submitting your Pull Request, please make sure you have read the [Guidelines for Submitting Pull Requests](https://github.com/pc2ccs/pc2v9/wiki/Guidelines-for-Submitting-Pull-Requests).  Then please provide the following information:

### Description of what the PR does

### Issue which the PR addresses
fixes #968 and #995 

### Environment in which the PR was developed (OS,IDE, Java version, etc.)
Windows 11, Eclipse 2021-12 R, JDK 8u381 (1.8)

### Precise steps for _testing_ the PR (i.e., how to demonstrate that it works correctly)
For #968 open admin or server. Then select reports. Select Scoreboard JSON from reports. Then export report contents. Save the pop up. Check the file download. Observe that time for solved problems are not 0 anymore. 

For #995 Before the method createContestStandings(String xmlString) .......core/standings/ScoreboardUtilities.java returns ContestStandings object compare the object and xml string. Informations on groups and problems that are not there is there. That point of the code can be reached by attempting to export Scoreboard JSON report from admin or server.

2024-08-05 04:20 UTC, SamanwaySadhu approved these changes
Reviewed only code changes and not functionality.

2024-08-15 20:22 UTC, johnbrvc commented on src/edu/csus/ecs/pc2/core/standings/GroupList.java
> +            // TODO pass a log into this class so we can do proper logging
You should be able to use StaticLog.getLog().

2024-08-24 16:29 UTC, johnbrvc requested changes
In the generated scoreboard json report, if a team attempts a problem, but does not solve it, the time property is set to **-1**.  This is probably because in the `DSA.calcProblemScoreData`, it initialized `solutionTime = -1`.  If it never finds a solved submissions for the problem, this is the value that gets set as the time for problem.  

The correct thing to do is if the `solved `property is `false`, **LEAVE OUT** the `time `property altogether. It should not appear.
```
{
   "rank": 122,
   "team_id": 46090,
   "score": {
      "total_time": 31,
      "num_solved": 1
   },
   "problems": [
   {
      "solved": false,
      "num_judged": 1,
      "time": -1,
      "problem_id": "turningred",
      "num_pending": 0
   },
```
would be:
```
{
   "rank": 122,
   "team_id": 46090,
   "score": {
      "total_time": 31,
      "num_solved": 1
   },
   "problems": [
   {
      "solved": false,
      "num_judged": 1,
      "problem_id": "turningred",
      "num_pending": 0
   },
```

Everything else seems to work, so once this is fixed, I will approve it.

2024-08-28 03:39 UTC, kkarakas commented
> In the generated scoreboard json report, if a team attempts a problem, but does not solve it, the time property is set to **-1**. This is probably because in the `DSA.calcProblemScoreData`, it initialized `solutionTime = -1`. If it never finds a solved submissions for the problem, this is the value that gets set as the time for problem.
> 
> The correct thing to do is if the `solved `property is `false`, **LEAVE OUT** the `time `property altogether. It should not appear.
> 
> ```
> {
>    "rank": 122,
>    "team_id": 46090,
>    "score": {
>       "total_time": 31,
>       "num_solved": 1
>    },
>    "problems": [
>    {
>       "solved": false,
>       "num_judged": 1,
>       "time": -1,
>       "problem_id": "turningred",
>       "num_pending": 0
>    },
> ```
> 
> would be:
> 
> ```
> {
>    "rank": 122,
>    "team_id": 46090,
>    "score": {
>       "total_time": 31,
>       "num_solved": 1
>    },
>    "problems": [
>    {
>       "solved": false,
>       "num_judged": 1,
>       "problem_id": "turningred",
>       "num_pending": 0
>    },
> ```
> 
> Everything else seems to work, so once this is fixed, I will approve it.

Implemented this, is this the case for DOMjudge? Do they ignore time if it is not solved in their JSON?

2024-08-28 14:20 UTC, johnbrvc commented
> > In the generated scoreboard json report, if a team attempts a problem, but does not solve it, the time property is set to **-1**. This is probably because in the `DSA.calcProblemScoreData`, it initialized `solutionTime = -1`. If it never finds a solved submissions for the problem, this is the value that gets set as the time for problem.
> > The correct thing to do is if the `solved `property is `false`, **LEAVE OUT** the `time `property altogether. It should not appear.
> > ```
> > {
> >    "rank": 122,
> >    "team_id": 46090,
> >    "score": {
> >       "total_time": 31,
> >       "num_solved": 1
> >    },
> >    "problems": [
> >    {
> >       "solved": false,
> >       "num_judged": 1,
> >       "time": -1,
> >       "problem_id": "turningred",
> >       "num_pending": 0
> >    },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > would be:
> > ```
> > {
> >    "rank": 122,
> >    "team_id": 46090,
> >    "score": {
> >       "total_time": 31,
> >       "num_solved": 1
> >    },
> >    "problems": [
> >    {
> >       "solved": false,
> >       "num_judged": 1,
> >       "problem_id": "turningred",
> >       "num_pending": 0
> >    },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Everything else seems to work, so once this is fixed, I will approve it.
> 
> Implemented this, is this the case for DOMjudge? Do they ignore time if it is not solved in their JSON?

DOMjudge leaves it out if the problem hasn't been solved.

2024-08-29 12:28 UTC, johnbrvc commented
My only concern is that it is still possible that the "time" can still be set to -1 (even though the scoreboard json will never display it).  Is there any other place in the code where that could be an issue?  Another problem is, a time of value 0 is technically possible, so, it seems that the "time" field is only valid if solved is true, so it should be up to the code that would potentially use the time value to make sure that the problem was solved, similar to what you just added for the json scoreboard generation.  I dont think we have to change any more code to address this at the moment, so I am prepared to approve it as it, after I test it.

2024-09-03 15:42 UTC, johnbrvc approved these changes
Looks ok, and seems to work.

2024-09-03 15:43 UTC, merged